version: '3'

services:
  node-app:
    build: .
    image: node-app
    container_name: node-app
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - node-app-network
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 20s && npm run dev"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - node-app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb

networks:
  node-app-network:
    driver: bridge
