on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        uses: actions/checkout@v4
        run: docker compose up --build -d && sleep 10 

      - name: Check the app
        uses: actions/checkout@v4
        run: curl -sSf http://localhost:8080

      - name: Tear down the app
        uses: actions/checkout@v4
        run: docker compose down


