on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose up --build -d
          sleep 60
          curl http://localhost:8080
          docker compose down

