on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up --build -d && sleep 10 

      - uses: actions/checkout@v4
      - run: curl -sSf http://localhost:8080

      - uses: actions/checkout@v4
      - run: docker compose down


