on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start containers
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml
          log-level: info
          build: true
          detached: true