on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build App, test and tear down
        run: |
          docker compose up --build -d \
          && sleep 10 \
          && curl -sSf http://localhost:8080 \
          && docker compose down


